name: main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        sudo apt install python3-venv
        python3 -m venv ../.venv
        source ../.venv/bin/activate
        pip install -r requirements.txt
        pip install black
        pip install codecov
        pip install coverage
        black --check ./*/*.py
        coverage run --omit="*/tests*" -m unittest
        deactivate
